spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studoglasnik
    username: studoglasnik
    password: studOGLAS!12
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  liquibase:
    change-log: classpath:/database/database-changelog.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    jwt:
      secret: studoglasnikSecretKey

hr.tvz.ntovernic.studoglasnik:
  picture-folder: C:/Users/Nikola/IdeaProjects/studoglasnik/pictures
  user-picture-folder: C:/Users/Nikola/IdeaProjects/studoglasnik/pictures/user