version: '3.5'

services:
  postgres:
    container_name: studoglasnik
    image: postgres:latest
    environment:
      POSTGRES_USER: studoglasnik
      POSTGRES_PASSWORD: studOGLAS!12
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local